CREATE TABLE `inspect`.`new_table` (
  `orderid` INT NOT NULL,
  `custel` VARCHAR(45) NULL,
  `qualtel` VARCHAR(45) NULL,
  `excedate` VARCHAR(45) NULL,
  `date` VARCHAR(45) NULL,
  `factoryname` VARCHAR(45) NULL,
  `factotyaddress` VARCHAR(45) NULL,
  `factoryman` VARCHAR(45) NULL,
  `factorytel` VARCHAR(45) NULL,
  `profile` VARCHAR(45) NULL,
  `file` VARCHAR(45) NULL,
  `reportfile` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `fee` VARCHAR(45) NULL,
  `cost` VARCHAR(45) NULL,
  `othercost` VARCHAR(45) NULL,
  `profit` VARCHAR(45) NULL,
  PRIMARY KEY (`orderid`));
